name: Deploy

on:
  workflow_dispatch:
    inputs:
      deployEnvs:
        description: 'Environment to deploy to'
        required: true
        default: '["prod1","prod2"]'
        type: string

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test composite call
        uses: ./.github/actions/test-composite
          
